"""Versioned prompts used by controlled agent workflows."""

from tradingagents.agents.prompts.sprint4 import (
    REGIME_ANALYST_PROMPT,
    REGIME_ANALYST_PROMPT_VERSION,
    STRATEGY_GENERATOR_PROMPT,
    STRATEGY_GENERATOR_PROMPT_VERSION,
)
from tradingagents.agents.prompts.sprint6 import (
    BEAR_RESEARCHER_PROMPT,
    BULL_RESEARCHER_PROMPT,
    DEBATE_SYNTHESIZER_PROMPT,
    PERFORMANCE_ANALYST_PROMPT,
    REFINEMENT_PROMPT,
    RISK_MANAGER_PROMPT,
    SPRINT6_PROMPT_VERSION,
    STRATEGY_CRITIC_PROMPT,
)

__all__ = [
    "REGIME_ANALYST_PROMPT",
    "REGIME_ANALYST_PROMPT_VERSION",
    "STRATEGY_GENERATOR_PROMPT",
    "STRATEGY_GENERATOR_PROMPT_VERSION",
    "BEAR_RESEARCHER_PROMPT",
    "BULL_RESEARCHER_PROMPT",
    "DEBATE_SYNTHESIZER_PROMPT",
    "PERFORMANCE_ANALYST_PROMPT",
    "REFINEMENT_PROMPT",
    "RISK_MANAGER_PROMPT",
    "SPRINT6_PROMPT_VERSION",
    "STRATEGY_CRITIC_PROMPT",
]
